server.port=${PORT:8080}
# Ensure application is run in Vaadin 14/npm mode
vaadin.compatibilityMode = false
logging.level.org.atmosphere = warn
#extra 
spring.mustache.check-template-location = false
spring.application.name= 'Freelancingpeter'
spring.mvc.format.date='dd-MM-yyyy'
server.servlet.application-display-name='Freelancingpeter'

# To improve the performance during development. 
# For more information https://vaadin.com/docs/v14/flow/spring/tutorial-spring-configuration.html#special-configuration-parameters
# vaadin.whitelisted-packages= org/vaadin/example
